# Generated by Django 4.0.6 on 2022-07-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
